<?php echo $this->doctype() ?>
<html>
<head>
  <?php echo $this->headMeta(); ?>
  <?php echo $this->headTitle(); ?>
  <?php echo $this->headLink(); ?>
  <?php echo $this->headStyle(); ?>
  <?php echo $this->headScript(); ?>
</head>
<body>
  <header>
    <h1><?php echo $this->siteTile; ?></h1>
  </header>
  <nav>
    <ul>
      <li>integral</li>
      <li>meio-turno</li>
      <li>freelance</li>
      <li>estágio</li>
      <li>remoto</li>
    </ul>
  </nav>
  <section>
    <?php echo $this->layout()->content; ?>
  </section>
  <section></section>
  <footer>
    <?php echo $this->siteTile; ?>
  </footer>
</body>
</html>
